<div class="main-content">
	<div class="wrap-content container" id="container">
		<!-- start: BREADCRUMB -->
		<div class="breadcrumb-wrapper">
			<h4 class="mainTitle no-margin"><?= $this->Translate("Blocking of purses") ?></h4>
			<ul class="pull-right breadcrumb">
				<li>
					<a href="index.html"><i class="fa fa-home margin-right-5 text-large text-dark"></i>Home</a>
				</li>
				<li>
					Tables
				</li>
				<li>
					Basic
				</li>
			</ul>
		</div>
		<!-- end: BREADCRUMB -->
		
		<!-- start: CONTEXTUAL CLASSES -->
		<div class="container-fluid container-fullw">
			<div class="row">
				<!-- start: ICONS AND HELPERS -->
				<div class="container-fluid container-fullw">
					<div class="row">
						<div class="col-md-12">
							<div class="panel panel-white">
								<div class="panel-body">
									<?= $this->sForm ?>
									
									<? if ($this->purse) :?>
										<h5 class="over-title margin-bottom-15"><?= $this->Translate("purse") ?>: <?=$this->purse->purseName()?>   <?= $this->Translate("balace") ?> <?=$this->purse->getBalance()?></h5>

										<div class="formwrapper">
											<form action='<?= $this->bForm->getAction( ) ?>' method='<?= $this->bForm->getMethod( ) ?>'  enctype='<?= $this->bForm->getEnctype( ) ?>' >
												<?= $this->bForm->purse ?>    	
												<table class="form_table table table-hover">
													<tr>
														<td><?= $this->bForm->blocked->getLabel() ?></td>				
														<td>
															<? $options=$this->bForm->blocked->getMultiOptions( ) ?> 
															<? $value=$this->bForm->blocked->getValue( ) ?>
															<input type="radio" class="radio" name="blocked" id="blocked-0" value="0" <? echo (!$value) ? "checked='checked'" : "" ?>/> <label><?= $options[0] ?></label><br />
															<input type="radio" class="radio" name="blocked" id="blocked-1" value="1" <? echo ($value) ? "checked='checked'" : "" ?> /> 
															<label><?= $options[1] ?>
																<em>
																	<? if ($this->purse->blocked_description) :?>
																		- <?=$this->purse->blocked_description?> 
																	<? endif; ?>
																</em>
															</label>
														</td>
													</tr>
													<tr>
														<?= $this->bForm->note ?>
													</tr>
													<tr>
														<td></td>
														<td>
															<?= $this->bForm->Set ?>
														</td>
													</tr>
												</table>
											</form> 
										</div>
									<? endif; ?>	
									
									<?= $this->message() ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>