<?php if ( count($this->balance)>0 ) : ?>
	<h3 class="m-b-lg"></h3>
	
	<div class="purses">

	<table class="table table-striped table-hover" id="profile-purses">
		<tbody>		
		<?php foreach ($this->balance as $cur) : ?>
			<tr class="info text-color">
				<td class="center"><img src="<?= $cur->getIcon() ?>" class="img-rounded" alt="image" /></td>
				<td><?= $cur->purseName() ?> </td>
				<td class="hidden-xs center"><?= $cur->getBalance() ?> <?= $cur->getSymbol() ?></td>
				<td class="hidden-xs center"><a href="#" rel="nofollow" target="_blank"> Пополнить </a></td>
				<td class="hidden-xs center"><a href="#" rel="nofollow" target="_blank"> Перевести </a></td>
				<td class="hidden-xs center"><a href="#" rel="nofollow" target="_blank"> Вывести </a></td>	
			</tr>
		<?php endforeach; ?>		
		</tbody>
	</table>
		
	</div>
<?php endif; ?>   
